run:
  deadline: 60s
  skip-dirs:
    - dist
    - hack
    - message-api-spec

linters:
  enable:
  - misspell
  - gofmt

linters-settings:
  gofmt:
    simplify: false

issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - errcheck
