---
language: go
go:
  - 1.x
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - make tools
script:
  - hack/coverage.sh --coveralls
  - make
  - make vendor-status
notifications:
  email: false
