---
language: go
go:
  - 1.x
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - make tools
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls
      -ignore=publisher/pb/rpc.pb.go,broker/message/specdata/specdata.go
      -service=travis-ci
  - make
  - make vendor-status
notifications:
  email: false
