---

dist: bionic

sudo: false

language: go

branches:
  only:
    - "master"

git:
  depth: 3
  quiet: true
  submodules: true

notifications:
  email: false

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/.local
    - $HOME/gopath/pkg/mod

jobs:
  include:
    - os: linux
      go: "1.13.x"
      env:
        - TEST_TYPE=unit
      script:
        - go mod download
        - make tools
        - make build testrace
        - make fmt
        - make lint
        - hack/coverage.sh --coveralls
    - os: linux
      go: "1.13.x"
      env:
        - TEST_TYPE=integration
      services:
        - docker
      script:
        - go mod download
        - pip install --user --quiet awscli
        - make test-integration
