---

dist: bionic

sudo: false

language: go

branches:
  only:
    - "master"

git:
  depth: 3
  quiet: true
  submodules: false

notifications:
  email: false

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

jobs:
  include:
    - os: linux
      go: "1.12.x"
      env:
        - TEST_TYPE=unit
        - GO111MODULE=on
      script:
        - go mod download
        - make tools
        - make build testrace
        - make fmt
        - make lint
        - hack/coverage.sh --coveralls
    - os: linux
      go: "1.12.x"
      env:
        - TEST_TYPE=integration
        - GO111MODULE=on
      services:
        - docker
      script:
        - go mod download
        - make install
        - docker ps
