version: "3"

services:

  localstack:
    # v0.10.0 or newer not working for me,
    # SQS eventually stops delivering messages.
    image: "localstack/localstack:0.11.3"
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - "SERVICES=s3,dynamodb,sqs,sns"
